--- #YAML:1.0
name:               Net-MyOpera
version:            0.02
abstract:           a Perl interface to the My Opera Community API
author:
    - Cosimo Streppone <cosimo@opera.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:             0
    LWP::UserAgent:  0
    Net::OAuth:      0.25
    Test::More:      0
    URI:             0
    URI::Escape:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
